name: Deploy to Glitch

on:
  push:
    branches:
      - main # Or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history to avoid shallow clone issues

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the version your project requires

      - name: Set up git for Glitch
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Add Glitch remote
        run: git remote add glitch ${{ secrets.GLITCH_GIT_URL }}

      - name: Push to Glitch
        run: |
          git push --force glitch main:master
        env:
          GLITCH_GIT_URL: ${{ secrets.GLITCH_GIT_URL }}
