name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch full history

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Glitch
        env:
          GLITCH_PROJECT_NAME: ${{ secrets.GLITCH_PROJECT_NAME }}
          GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
        run: |
          git remote add glitch https://${GLITCH_TOKEN}@api.glitch.com/git/${GLITCH_PROJECT_NAME}
          git push --force glitch main
